services:
  traefik:
    image: traefik:v3.5
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:9000
      - --log.level=INFO
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

  backend:
    build:
      context: ./../../
      dockerfile_inline: |
        FROM sbtscala/scala-sbt:eclipse-temurin-24.0.1_9_1.11.4_3.7.2 AS builder
        WORKDIR /app
        COPY . .
        RUN apt-get update && apt-get install -y unzip
        RUN sbt zio-sveltekit-backend/Universal/packageBin
        RUN unzip example/zio-sveltekit/backend/target/universal/zio-sveltekit-backend-0.1.0.zip -d /app/zio-sveltekit-backend/

        FROM eclipse-temurin:24-jre
        COPY --from=builder /app/zio-sveltekit-backend/zio-sveltekit-backend-0.1.0/ /app/zio-sveltekit-backend/
        EXPOSE 8080
        CMD ["/app/zio-sveltekit-backend/bin/zio-sveltekit-backend"]

    container_name: zio-backend
    env_file:
      - ../../.env
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`) &&
        PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    depends_on:
      - traefik

  frontend:
    build:
      context: ./frontend
      dockerfile_inline: |
        FROM oven/bun:1 AS builder
        WORKDIR /app
        COPY . .
        RUN bun install --frozen-lockfile
        RUN bun run build

        FROM nginx:alpine
        COPY --from=builder /app/build /usr/share/nginx/html
        COPY nginx.conf /etc/nginx/nginx.conf
        EXPOSE 80
        CMD ["nginx", "-g", "daemon off;"]

    container_name: svelte-frontend
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - traefik

networks:
  app-network:
    driver: bridge
