name: Uploading dependency graph

on:
  push:
    branches:
      - main

jobs:
  compile-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@v2
        with:
          modules-ignore: |
            zio-form-oauth_2.13 zio-sveltekit-backend_2.13 zio-jwt_2.13 root_2.13
          configs-ignore: scala-doc-tool
